version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - unconvert
    - unparam
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Template parsing is slow, so some global templates are ok
      - linters:
          - gochecknoglobals
        text: .*Template is a global variable
        source: .*Template = template\.Must\(.*
      # Allow const duplication in tests.
      - linters:
          - goconst
        path: .+_test\.go
formatters:
  enable:
    - gofmt
