version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
        text: .*Template is a global variable
        source: .*Template = template\.Must\(.*
      - linters:
          - goconst
        path: .+_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
